import type { AppState } from "./types";

const CS = "club_coton";
const CY = "club_canon";
const CD = "club_colombe";

function p(
  id: string,
  clubId: string,
  name: string,
  position: AppState["players"][number]["position"],
  number: number,
  age: number,
  nationality: string,
  extras: Partial<AppState["players"][number]> = {},
): AppState["players"][number] {
  const fatigue = extras.fatigue ?? 38 + ((id.charCodeAt(id.length - 1) * 7) % 50);
  return {
    id,
    clubId,
    name,
    position,
    number,
    age,
    nationality,
    height: extras.height ?? 175 + (number % 18),
    weight: extras.weight ?? 68 + (number % 16),
    foot: extras.foot ?? (number % 3 === 0 ? "Gauche" : "Droit"),
    marketValue: extras.marketValue ?? 80_000 + number * 12_000 + age * 4_000,
    fatigue,
    form: extras.form ?? 62 + (number % 30),
    contractEnd: extras.contractEnd ?? "2027-06-30",
    salary: extras.salary ?? 450_000 + number * 20_000,
    photo: extras.photo ?? "",
    listed: extras.listed ?? false,
    stats: extras.stats ?? {
      matches: 18 + (number % 10),
      goals: position === "BU" || position === "MOC" ? 4 + (number % 8) : number % 4,
      assists: 2 + (number % 6),
      minutes: 1200 + number * 40,
      yellow: number % 5,
      red: number % 9 === 0 ? 1 : 0,
      passPct: 74 + (number % 18),
      duelsWon: 48 + (number % 30),
      distanceKm: 8.4 + (number % 5) * 0.6,
      sprintTop: 31 + (number % 6),
    },
    career: extras.career ?? [
      { season: "2023/24", club: "Coton Sport", matches: 22, goals: 3 },
      { season: "2024/25", club: "Coton Sport", matches: 26, goals: 5 },
      { season: "2025/26", club: "Coton Sport", matches: 18, goals: 4 },
    ],
  };
}

export function createSeed(): AppState {
  const players = [
    p("pl_01", CS, "Fabrice Ondoa", "GB", 1, 30, "Cameroun", { marketValue: 420000, fatigue: 22, contractEnd: "2027-06-30" }),
    p("pl_02", CS, "Jean-Charles Castelletto", "DC", 4, 31, "Cameroun", { marketValue: 3800000, fatigue: 41 }),
    p("pl_03", CS, "Nouhou Tolo", "DG", 3, 29, "Cameroun", { marketValue: 2500000, fatigue: 68 }),
    p("pl_04", CS, "Collins Fai", "DD", 2, 33, "Cameroun", { marketValue: 450000, fatigue: 77, contractEnd: "2026-12-31" }),
    p("pl_05", CS, "André-Frank Zambo", "MDC", 6, 30, "Cameroun", { marketValue: 1800000, fatigue: 55 }),
    p("pl_06", CS, "Pierre Kunde", "MC", 8, 31, "Cameroun", { marketValue: 900000, fatigue: 49 }),
    p("pl_07", CS, "Karl Toko Ekambi", "AG", 7, 33, "Cameroun", { marketValue: 1200000, fatigue: 61, listed: true }),
    p("pl_08", CS, "Nicolas Moumi Ngamaleu", "AD", 11, 30, "Cameroun", { marketValue: 3500000, fatigue: 33 }),
    p("pl_09", CS, "Vincent Aboubakar", "BU", 9, 34, "Cameroun", { marketValue: 800000, fatigue: 82, contractEnd: "2026-06-30" }),
    p("pl_10", CS, "Bryan Mbeumo", "MOC", 10, 26, "Cameroun", { marketValue: 45000000, fatigue: 44 }),
    p("pl_11", CS, "Chester Nfor", "BU", 19, 22, "Cameroun", { marketValue: 180000, fatigue: 29, contractEnd: "2028-06-30" }),
    p("pl_12", CS, "Samuel Kotto", "DC", 5, 21, "Cameroun", { marketValue: 220000, fatigue: 36 }),
    p("pl_13", CS, "Yvan Neyou", "MDC", 14, 29, "Cameroun", { marketValue: 1600000, fatigue: 52 }),
    p("pl_14", CS, "Olivier Mbaizo", "DD", 17, 28, "Cameroun", { marketValue: 700000, fatigue: 40 }),
    p("pl_15", CS, "Ignatius Ganago", "BU", 21, 27, "Cameroun", { marketValue: 2500000, fatigue: 58 }),
    p("pl_16", CY, "André Onana", "GB", 1, 30, "Cameroun", { marketValue: 28000000, fatigue: 31 }),
    p("pl_17", CY, "Michael Ngadeu", "DC", 5, 35, "Cameroun", { marketValue: 300000, fatigue: 71, contractEnd: "2026-11-30" }),
    p("pl_18", CY, "Christian Bassogog", "AD", 13, 30, "Cameroun", { marketValue: 1100000, fatigue: 47 }),
    p("pl_19", CY, "Stéphane Bahoken", "BU", 9, 34, "Cameroun", { marketValue: 400000, fatigue: 64 }),
    p("pl_20", CY, "Martin Hongla", "MC", 8, 28, "Cameroun", { marketValue: 2200000, fatigue: 39 }),
    p("pl_21", CD, "Didier Lamkel Zé", "AG", 11, 29, "Cameroun", { marketValue: 900000, fatigue: 53 }),
    p("pl_22", CD, "Jean Onana", "MDC", 6, 26, "Cameroun", { marketValue: 3500000, fatigue: 45 }),
    p("pl_23", CD, "Faris Pemi Moumbagna", "BU", 9, 25, "Cameroun", { marketValue: 2800000, fatigue: 28 }),
  ];

  return {
    clubs: [
      { id: CS, name: "Coton Sport de Garoua", shortName: "Coton Sport", league: "Elite One", city: "Garoua", country: "Cameroun", founded: 1986, stadium: "Stade Roumdé Adjia", colors: ["#16a34a", "#ffffff"], logoLetter: "CS" },
      { id: CY, name: "Canon Sportif de Yaoundé", shortName: "Canon", league: "Elite One", city: "Yaoundé", country: "Cameroun", founded: 1930, stadium: "Stade Ahmadou Ahidjo", colors: ["#dc2626", "#15803d"], logoLetter: "CY" },
      { id: CD, name: "Colombe du Dja et Lobo", shortName: "Colombe", league: "Elite One", city: "Sangmélima", country: "Cameroun", founded: 1995, stadium: "Stade Municipal", colors: ["#2563eb", "#fbbf24"], logoLetter: "CD" },
    ],
    users: [
      { id: "u_super", email: "emma.t@example.net", password: "Super123!", name: "Bodi Awono", role: "super_admin", clubId: null, avatar: "BA", status: "active", lastLogin: "2026-09-29T08:12:00Z" },
      { id: "u_admin", email: "hannah.h@example.com", password: "Admin123!", name: "Paul Essomba", role: "club_admin", clubId: CS, avatar: "PE", status: "active", lastLogin: "2026-09-29T07:40:00Z" },
      { id: "u_coach", email: "iris.p@example.org", password: "Coach123!", name: "Marc Brys", role: "coach", clubId: CS, avatar: "MB", status: "active", lastLogin: "2026-09-28T18:22:00Z" },
      { id: "u_staff", email: "walt.e@example.net", password: "Staff123!", name: "Dr. Léa Fouda", role: "staff", clubId: CS, avatar: "LF", status: "active", lastLogin: "2026-09-29T06:55:00Z" },
      { id: "u_player", email: "samuel.w@example.com", password: "Player123!", name: "Chester Nfor", role: "player", clubId: CS, playerId: "pl_11", avatar: "CN", status: "active", lastLogin: "2026-09-28T21:10:00Z" },
      { id: "u_admin_cy", email: "oscar.d@example.net", password: "Admin123!", name: "Joseph Atangana", role: "club_admin", clubId: CY, avatar: "JA", status: "active", lastLogin: "2026-09-27T12:00:00Z" },
    ],
    players,
    contracts: players.map((pl, i) => ({
      id: `ct_${pl.id}`,
      playerId: pl.id,
      clubId: pl.clubId,
      start: "2024-07-01",
      end: pl.contractEnd,
      salary: pl.salary,
      bonus: 50_000,
      releaseClause: pl.marketValue * 2,
      status: pl.contractEnd.startsWith("2026") ? "expiring" : "active",
      clauses: i % 2 === 0 ? ["Clause de revente 20%", "Bonus buts"] : ["Option +1 an", "Prime titre"],
    })),
    matches: [
      { id: "m1", clubId: CS, opponent: "Canon Yaoundé", competition: "Elite One", date: "2026-09-21", venue: "Domicile", scoreHome: 2, scoreAway: 1, analyzed: true, formation: "4-3-3" },
      { id: "m2", clubId: CS, opponent: "Colombe", competition: "Elite One", date: "2026-09-14", venue: "Extérieur", scoreHome: 0, scoreAway: 0, analyzed: true, formation: "4-2-3-1" },
      { id: "m3", clubId: CS, opponent: "PWD Bamenda", competition: "Elite One", date: "2026-10-05", venue: "Domicile", scoreHome: null, scoreAway: null, analyzed: false, formation: "4-3-3" },
      { id: "m4", clubId: CS, opponent: "Union Douala", competition: "Coupe du Cameroun", date: "2026-09-07", venue: "Extérieur", scoreHome: 1, scoreAway: 3, analyzed: true, formation: "3-5-2" },
      { id: "m5", clubId: CS, opponent: "Aigle Royal", competition: "Elite One", date: "2026-08-31", venue: "Domicile", scoreHome: 4, scoreAway: 0, analyzed: true, formation: "4-3-3" },
      { id: "m6", clubId: CY, opponent: "Coton Sport", competition: "Elite One", date: "2026-09-21", venue: "Extérieur", scoreHome: 2, scoreAway: 1, analyzed: true, formation: "4-4-2" },
    ],
    videos: [
      { id: "v1", matchId: "m1", clubId: CS, title: "But Aboubakar 23'", minute: 23, type: "highlight", playerId: "pl_09", notes: "Frappe du gauche, angle fermé." },
      { id: "v2", matchId: "m1", clubId: CS, title: "Transition 4-3-3 → pressing", minute: 41, type: "tactical", notes: "Déclenchement du pressing après perte haute." },
      { id: "v3", matchId: "m1", clubId: CS, title: "Sprint Ngamaleu", minute: 67, type: "individual", playerId: "pl_08", notes: "34.2 km/h, débordement + centre." },
      { id: "v4", matchId: "m5", clubId: CS, title: "Hat-trick Mbeumo", minute: 78, type: "highlight", playerId: "pl_10", notes: "Troisième but, 1v1 gardien." },
      { id: "v5", matchId: "m4", clubId: CS, title: "Faiblesse côté droit", minute: 12, type: "tactical", notes: "Isolement Fai, 2v1 répétés." },
    ],
    medical: [
      { id: "md1", playerId: "pl_09", date: "2026-09-24", type: "prevention", diagnosis: "Charge articulaire genou D", protocol: "Décharge 48h + isométriques", status: "en_cours", injuryRisk: 72 },
      { id: "md2", playerId: "pl_04", date: "2026-09-22", type: "visite", diagnosis: "Fatigue neuromusculaire", protocol: "Sommeil + nutrition + repos relatif", status: "ouvert", injuryRisk: 81 },
      { id: "md3", playerId: "pl_03", date: "2026-09-18", type: "blessure", diagnosis: "Contracture ischio G", protocol: "Proprio + renforcement excentrique 10j", status: "en_cours", injuryRisk: 64 },
      { id: "md4", playerId: "pl_11", date: "2026-09-10", type: "visite", diagnosis: "Bilan pré-saison OK", protocol: "Maintien charge progressive", status: "clos", injuryRisk: 18 },
      { id: "md5", playerId: "pl_07", date: "2026-09-26", type: "recup", diagnosis: "DOMS post-match", protocol: "Cryothérapie + mobilité", status: "clos", injuryRisk: 34 },
    ],
    loads: players.filter((x) => x.clubId === CS).flatMap((pl) =>
      [0, 1, 2, 3, 4, 5, 6].map((d) => ({
        id: `ld_${pl.id}_${d}`,
        playerId: pl.id,
        date: `2026-09-${23 + d > 30 ? 23 : 23 + d}`.replace("2026-09-23", `2026-09-${String(23 + (d % 7)).padStart(2, "0")}`),
        session: d % 2 === 0 ? "Terrain" : "Gym",
        acute: 380 + (pl.fatigue * 3) + d * 12,
        chronic: 420 + pl.number * 4,
        gpsKm: 6 + (d % 4) + pl.number * 0.05,
        sprints: 12 + (d % 8),
        topSpeed: 30 + (d % 5),
      })),
    ),
    events: [
      { id: "e1", clubId: CS, title: "Elite One vs PWD Bamenda", type: "match", start: "2026-10-05T16:00:00", end: "2026-10-05T18:00:00", location: "Roumdé Adjia", team: "A", notes: "Briefing 14h", googleSynced: true },
      { id: "e2", clubId: CS, title: "Séance tactique 4-3-3", type: "entrainement", start: "2026-09-30T09:00:00", end: "2026-09-30T11:00:00", location: "Centre d'entraînement", team: "A", notes: "Pressing haut", googleSynced: true },
      { id: "e3", clubId: CS, title: "Suivi médical fatigue", type: "medical", start: "2026-09-30T14:00:00", end: "2026-09-30T16:00:00", location: "Infirmerie", team: "Staff", notes: "Aboubakar, Fai, Nouhou", googleSynced: false },
      { id: "e4", clubId: CS, title: "Réunion staff vidéo", type: "reunion", start: "2026-10-01T18:00:00", end: "2026-10-01T19:30:00", location: "Salle analyse", team: "Staff", notes: "Clips Canon", googleSynced: true },
      { id: "e5", clubId: CS, title: "Déplacement Bamenda", type: "deplacement", start: "2026-10-04T07:00:00", end: "2026-10-04T14:00:00", location: "Bus club", team: "A", notes: "Petit-déj 6h30", googleSynced: false },
      { id: "e6", clubId: CS, title: "U21 vs Renaissance", type: "match", start: "2026-10-03T15:00:00", end: "2026-10-03T17:00:00", location: "Annexe", team: "U21", notes: "", googleSynced: false },
    ],
    channels: [
      { id: "ch_staff", clubId: CS, name: "Staff technique", kind: "group", members: ["u_admin", "u_coach", "u_staff"] },
      { id: "ch_team", clubId: CS, name: "Groupe A", kind: "group", members: ["u_coach", "u_player", "u_admin"] },
      { id: "ch_news", clubId: CS, name: "Annonces officielles", kind: "announce", members: ["u_admin", "u_coach", "u_staff", "u_player"] },
      { id: "ch_dm", clubId: CS, name: "Coach ↔ Chester", kind: "dm", members: ["u_coach", "u_player"] },
    ],
    messages: [
      { id: "msg1", channelId: "ch_news", fromId: "u_admin", content: "Convocation A publiée pour PWD. Présence obligatoire au briefing 14h.", at: "2026-09-28T10:00:00Z" },
      { id: "msg2", channelId: "ch_staff", fromId: "u_staff", content: "Alerte fatigue : Aboubakar 82 et Fai 77. Repos relatif recommandé.", at: "2026-09-29T07:05:00Z" },
      { id: "msg3", channelId: "ch_staff", fromId: "u_coach", content: "OK. On sort Aboubakar du onze, Nfor titulaire.", at: "2026-09-29T07:12:00Z" },
      { id: "msg4", channelId: "ch_team", fromId: "u_coach", content: "Demain 9h, pressing 4-3-3. Vidéo 20 min avant.", at: "2026-09-29T16:40:00Z" },
      { id: "msg5", channelId: "ch_dm", fromId: "u_coach", content: "Chester, tu démarres vs PWD. Objectif : profondeur, pas trop de duels inutiles.", at: "2026-09-29T17:02:00Z" },
      { id: "msg6", channelId: "ch_dm", fromId: "u_player", content: "Compris coach. Je suis prêt.", at: "2026-09-29T17:08:00Z" },
    ],
    statuses: [
      { id: "st1", userId: "u_coach", text: "En salle vidéo — clips Canon", at: "2026-09-29T18:00:00Z", expiresAt: "2026-09-30T18:00:00Z" },
      { id: "st2", userId: "u_staff", text: "Infirmerie ouverte jusqu'à 19h", at: "2026-09-29T08:00:00Z", expiresAt: "2026-09-29T19:00:00Z" },
    ],
    scouts: [
      { id: "sc1", clubId: CS, targetName: "Emmanuel Bile", club: "APEJES", country: "Cameroun", position: "BU", age: 19, rating: 78, marketValue: 120000, notes: "Finisseur, bon timing. À suivre U21.", scout: "Réseau Yaoundé", date: "2026-09-12", status: "recommend" },
      { id: "sc2", clubId: CS, targetName: "Kwame Mensah", club: "Asante Kotoko", country: "Ghana", position: "MDC", age: 22, rating: 81, marketValue: 450000, notes: "Récupération + relance. Profil Elite One+.", scout: "West Africa Desk", date: "2026-09-20", status: "watch" },
      { id: "sc3", clubId: CS, targetName: "Ibrahim Diallo", club: "Stade Malien", country: "Mali", position: "DC", age: 24, rating: 76, marketValue: 280000, notes: "Aérien, agressif. Besoin de relance.", scout: "Sahel Network", date: "2026-08-30", status: "contacted" },
      { id: "sc4", clubId: CS, targetName: "Théo Bongonda", club: "Free agent", country: "RD Congo", position: "AD", age: 28, rating: 84, marketValue: 1800000, notes: "Expérience Europe. Salaire élevé.", scout: "Scout Réseau Mondial", date: "2026-09-25", status: "watch" },
      { id: "sc5", clubId: CS, targetName: "Ayoub El Kaabi", club: "Olympiacos", country: "Maroc", position: "BU", age: 33, rating: 86, marketValue: 4000000, notes: "Cible irréaliste. Veille marché uniquement.", scout: "Maghreb Desk", date: "2026-09-02", status: "watch" },
      { id: "sc6", clubId: CS, targetName: "Samuel Eto'o Jr", club: "Académie Kadji", country: "Cameroun", position: "MOC", age: 17, rating: 72, marketValue: 80000, notes: "Créativité, encore physique à construire.", scout: "Réseau Douala", date: "2026-09-18", status: "recommend" },
    ],
    transfers: [
      { id: "tr1", clubId: CS, playerName: "Karl Toko Ekambi", fromClub: "Coton Sport", toClub: "Al Ettifaq", value: 900000, status: "negociation", aiNote: "Offre 0,7 M sous-évaluée. Contre-proposition 1,1 M + 15% revente.", updated: "2026-09-28" },
      { id: "tr2", clubId: CS, playerName: "Chester Nfor", fromClub: "Coton Sport", toClub: "—", value: 180000, status: "veille", aiNote: "Valeur projetée +40% d'ici juin si temps de jeu > 1500 min.", updated: "2026-09-20" },
      { id: "tr3", clubId: CS, playerName: "Ibrahim Diallo", fromClub: "Stade Malien", toClub: "Coton Sport", value: 280000, status: "offre", aiNote: "Négociation IA : étaler 2 ans, clause de rachat 500 k.", updated: "2026-09-26" },
      { id: "tr4", clubId: CS, playerName: "Vincent Aboubakar", fromClub: "Coton Sport", toClub: "—", value: 800000, status: "veille", aiNote: "Contrat expire juin 2026. Renouveler 12 mois ou céder avant mercato.", updated: "2026-09-15" },
    ],
    tasks: [
      { id: "tk1", clubId: CS, title: "Plan de charge Fai & Aboubakar", assignee: "Dr. Léa Fouda", role: "staff", urgent: true, status: "open", due: "2026-09-30" },
      { id: "tk2", clubId: CS, title: "Briefing PWD — set pieces", assignee: "Marc Brys", role: "coach", urgent: true, status: "doing", due: "2026-10-04" },
      { id: "tk3", clubId: CS, title: "Renouvellement Aboubakar", assignee: "Paul Essomba", role: "club_admin", urgent: false, status: "open", due: "2026-10-15" },
      { id: "tk4", clubId: CS, title: "Clips vidéo pressing Canon", assignee: "VideoMaster AI", role: "ia", urgent: false, status: "done", due: "2026-09-22" },
    ],
    alerts: [
      { id: "al1", clubId: CS, type: "fatigue", severity: "critical", title: "Alerte fatigue — Aboubakar 82", body: "Email auto envoyé au staff. Seuil 75 dépassé.", at: "2026-09-29T06:40:00Z", playerId: "pl_09", read: false },
      { id: "al2", clubId: CS, type: "fatigue", severity: "critical", title: "Alerte fatigue — Collins Fai 77", body: "Repos relatif recommandé 48h.", at: "2026-09-29T06:41:00Z", playerId: "pl_04", read: false },
      { id: "al3", clubId: CS, type: "contrat", severity: "warn", title: "Renouvellement < 30 jours", body: "Ngadeu (Canon) et Fai approchent de l'échéance.", at: "2026-09-28T09:00:00Z", read: true },
      { id: "al4", clubId: CS, type: "tache", severity: "warn", title: "Tâche urgente assignée", body: "Plan de charge Fai & Aboubakar — staff médical.", at: "2026-09-29T07:00:00Z", read: false },
      { id: "al5", clubId: CS, type: "rapport", severity: "info", title: "Rapport mensuel septembre prêt", body: "Génération auto terminée. Envoi staff en attente.", at: "2026-09-29T05:00:00Z", read: true },
    ],
    agents: [
      { id: "ag_tactique", name: "Expert Tactique Football", tag: "Analyse & Briefings", description: "Génère analyses tactiques, briefings avant-match et recommandations stratégiques.", status: "online", lastAction: "Briefing PWD généré" },
      { id: "ag_scout", name: "Scout Réseau Mondial", tag: "150+ Pays", description: "Identifie talents émergents, marchés de transferts et connexions clubs/agents.", status: "online", lastAction: "6 cibles mises à jour" },
      { id: "ag_perf", name: "Analyste Performance", tag: "Temps Réel", description: "Surveille la charge, détecte anomalies et recommande ajustements.", status: "busy", lastAction: "ACR Fai > 1.4" },
      { id: "ag_video", name: "VideoMaster AI", tag: "Highlights Auto", description: "Analyse les vidéos, génère highlights et rapports vidéo tactiques.", status: "online", lastAction: "5 clips Canon indexés" },
      { id: "ag_coach", name: "Coach Développement", tag: "Plans Personnalisés", description: "Crée des plans individuels avec objectifs mesurables.", status: "idle", lastAction: "Plan Nfor v3" },
      { id: "ag_super", name: "Super Agent Royal Goose", tag: "Contrôle Total", description: "Orchestre les agents, coordonne les tâches et le monitoring global.", status: "online", lastAction: "Dispatch alerte fatigue" },
      { id: "ag_design", name: "Agent Design Visuel", tag: "Application IA", description: "Propose des améliorations d'interface et applique les designs approuvés.", status: "idle", lastAction: "Proposition heatmap v2" },
      { id: "ag_plan", name: "Coordinateur Planning", tag: "Optimisation Auto", description: "Gère calendriers multi-équipes, entraînements et synchronisation.", status: "online", lastAction: "Conflit U21 vs A résolu" },
    ],
    agentLogs: [
      { id: "lg1", agentId: "ag_super", action: "Alerte fatigue Aboubakar dispatchée vers staff + email", at: "2026-09-29T06:40:12Z", level: "warn" },
      { id: "lg2", agentId: "ag_perf", action: "Ratio aigu/chronique Fai = 1.47 — risque élevé", at: "2026-09-29T06:38:00Z", level: "warn" },
      { id: "lg3", agentId: "ag_video", action: "Highlights match Canon générés (3 clips)", at: "2026-09-22T21:14:00Z", level: "success" },
      { id: "lg4", agentId: "ag_tactique", action: "Simulation 4-3-3 vs 5-4-1 PWD terminée", at: "2026-09-29T11:02:00Z", level: "success" },
      { id: "lg5", agentId: "ag_scout", action: "Nouvelle reco : Emmanuel Bile (APEJES)", at: "2026-09-12T16:20:00Z", level: "info" },
      { id: "lg6", agentId: "ag_plan", action: "Google Calendar sync — 4 événements", at: "2026-09-29T08:00:00Z", level: "info" },
      { id: "lg7", agentId: "ag_coach", action: "Objectifs Nfor : 3 buts / 8 semaines", at: "2026-09-25T10:11:00Z", level: "success" },
      { id: "lg8", agentId: "ag_design", action: "Maquette dashboard fatigue proposée", at: "2026-09-27T19:44:00Z", level: "info" },
    ],
    briefings: [
      {
        id: "br1",
        clubId: CS,
        matchId: "m3",
        title: "Avant-match PWD Bamenda",
        formation: "4-3-3",
        createdAt: "2026-09-29T11:02:00Z",
        content:
          "PWD défend en 5-4-1 bas. Recommandation : largeur via Ngamaleu / Toko, 3e homme Zambo. Corners : 1er poteau Kotto. Pressing déclenché sur passe vers leur 6. Risque : transitions sur le dos de Fai — Mbaizo titulaire conseillé.",
      },
    ],
    designs: [
      { id: "ds1", clubId: CS, title: "Widget fatigue critique", summary: "Bandeau rouge dès 75+, CTA repos en 1 clic.", applied: false, createdAt: "2026-09-27T19:44:00Z" },
      { id: "ds2", clubId: CS, title: "Heatmap GPS plus lisible", summary: "Contraste + légende zones haute intensité.", applied: true, createdAt: "2026-09-20T12:00:00Z" },
    ],
    reports: [
      {
        id: "rp1",
        clubId: CS,
        month: "2026-09",
        sent: false,
        kpis: [
          { label: "Points Elite One", value: "16 / 7 j." },
          { label: "xG cumulé", value: "12.4" },
          { label: "Blessures", value: "1 ouverte" },
          { label: "Fatigue moyenne", value: "51" },
        ],
        narrative:
          "Septembre : 4 victoires, 1 nul, 1 défaite (Coupe). La charge a grimpé après Canon. L'IA recommande une micro-cycle de décharge avant PWD et le renouvellement d'Aboubakar.",
      },
    ],
    audit: [
      { id: "au1", at: "2026-09-29T07:12:00Z", user: "Marc Brys", action: "MAJ onze vs PWD", entity: "Match m3", clubId: CS },
      { id: "au2", at: "2026-09-29T06:40:12Z", user: "Système IA", action: "Email alerte fatigue", entity: "Joueur pl_09", clubId: CS },
      { id: "au3", at: "2026-09-28T10:00:00Z", user: "Paul Essomba", action: "Annonce officielle", entity: "Canal ch_news", clubId: CS },
      { id: "au4", at: "2026-09-27T19:50:00Z", user: "Bodi Awono", action: "Connexion Super Admin", entity: "Auth", clubId: null },
    ],
    subscriptions: [
      { clubId: CS, plan: "elite", status: "active", renews: "2026-12-01", seats: 48 },
      { clubId: CY, plan: "starter", status: "trial", renews: "2026-10-15", seats: 12 },
      { clubId: CD, plan: "continent", status: "active", renews: "2027-01-01", seats: 80 },
    ],
  };
}
